language: ruby
cache:
  bundler: true
rvm:
  - 2.4.1
stages:
  - rubocop
  - test
jobs:
  include:
    - script: cp config/travis/hydra-ldap.yml config/hydra-ldap.yml && bundle exec rspec
    - stage: rubocop
      script: bundle exec rubocop
