language: ruby
cache:
  bundler: true
bundler_args: --without development debug
sudo: false
rvm:
  - 2.4.1
stages:
  - rubocop
  - test
jobs:
  include:
    - script: cp config/hydra-ldap.yml.sample config/hydra-ldap.yml && bundle exec rake
    - stage: rubocop
      script: pwd
